choco install -y GoogleGhrome
choco install -y grep
choco install -y AstroGrep
choco install -y WinMerge
choco install -y NeoVim
choco install -y mRemoteNG
choco install -y ConEmu
choco install -y Everything
choco install -y QTTabBar
choco install -y RocketChat
choco install -y LINQPad
choco install -y Git
choco install -y TortoiseSVN
